### PR TITLE
Fix docker image location in README.md

### PR DESCRIPTION
**Pull request by anshumg**
A part of: #194

### CODE REVIEW

**Comment by HoustonPutman** [comment]
So I think we should only change this one when we actually deploy it, because that link will just be broken otherwise.

**Comment by anshumg** [comment]
Yup, just created this for the future,

**Comment by anshumg** [comment]
Actually, let me mark this as draft so we don't accidentally merge this.

**Comment by HoustonPutman** [comment]
We have to say goodbye to our 200k download count 😢 

But hopefully we make it back soon!

**Pull request merged**
