### PR TITLE
Upgrading go-version to 1.20

### PR DESCRIPTION
**Pull request by sujeeth62**
Upgrading go-version to 1.20

### CODE REVIEW

**Comment by sujeeth62** [comment]
@HoustonPutman - Please can you share why the build failed.

**Comment by HoustonPutman** [comment]
try running:

```
make mod-clean
make prepare
```

It should generate a new dependency_licenses.csv for you.

**Comment by sujeeth62** [comment]
> try running:
> 
> ```
> make mod-clean
> make prepare
> ```
> 
> It should generate a new dependency_licenses.csv for you.

I am not sure why but above commands are not generating the dependency_licenses csv file.

**Comment by sujeeth62** [comment]
Please provide the approval for workflow to run.

**Comment by sujeeth62** [comment]
@HoustonPutman - Please let me know if anything further need to be done on this.

**Comment by HoustonPutman** [comment]
Thanks for the contribution @sujeeth62 !

**Comment by sujeeth62** [comment]
> Thanks for the contribution @sujeeth62 !

Thank you for your support @HoustonPutman

**Pull request merged**
