### PR TITLE
Adding autoscaling policy configuration for Collection.

### LINKED ISSUE #52: Allow setting autoscaling policy
When creating a collection I would like to be able to create and associate an autoscaling policy.

https://lucene.apache.org/solr/guide/7_7/solrcloud-autoscaling-policy-preferences.html

### LINKED ISSUE #55: More configuration options
Hi there,

We are considering using Bloomberg operator for our SOLR cluster but there are a few things we need to configure that the operator doesn't provide for us:

- Support of configuration for security contexts on stateful sets 
- Custom annotations on services and stateful sets
- Adding our data volumes to stateful sets
- Setting policy name on collections

### PR DESCRIPTION
**Pull request by HoustonPutman**
*Issue number of the reported bug or feature request: Resolves #55, Resolves #52*

**Describe your changes**
Allowing for the setting of collection autoscaling policies via the Collection CRD.

### CODE REVIEW

**Comment by AceHack** [comment]
Will I be able to target Avialiabily Zones in AWS EKS as part of the policy?

**Comment by AceHack** [comment]
I would really like to set a policy that looks like

`{"replica": "#EQUAL", "shard": "#EACH", "sysprop.zone": "#ANY"}
`
or

`{"replica": "#EQUAL", "shard": "#EACH", "sysprop.zone": ["us-east-1a", "us-east-1b", "us-east-1c"]}
`

**Comment by AceHack** [comment]
More info
https://lucene.472066.n3.nabble.com/Rule-based-replication-or-sharding-td4407125.html#a4407660

**Comment by sepulworld** [comment]
This sounds great! We deal with really slow scale ups because new nodes don’t land in the right AZ where EBS is. 

“where "az" is a sysprop while starting each solr instance ( -Daz=us-east-1 )”
Sounds like the stateful set needs to pass a unique startup property to the instance depending on if it is in AWS and what AZ it is in. Might also be similar for Azure and GCP.
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Feb 21, 2020 at 7:30 AM -0800, "Aaron Stainback" <notifications@github.com> wrote:












More info

https://lucene.472066.n3.nabble.com/Rule-based-replication-or-sharding-td4407125.html#a4407660

**Comment by HoustonPutman** [comment]
Yeah, I've thought about that for a while. Maybe we can add Kubernetes Node labels to our Solr nodes somehow? 

How do y'all currently get solr to run across these availability zones? I'm assuming you have Kubernetes Node labels that describe which AZ each one is in, and you have Affinity rules setup to spread the solrcloud across them?

**Comment by HoustonPutman** [comment]
Looks like the adding Node Labels as Pod environment variables has been discussed for a while and nothing has been done about it yet. https://github.com/kubernetes/kubernetes/issues/40610

That's unfortunate.

**Comment by AceHack** [comment]
We've currently just created 3 separate stateful sets and each one is tied to one AZ and adds the appropriate zone property to the solr startup.  It's possible to read your AZ in an init container or as part of the pod startup, you'll have to call into the K8s APIs to get it.

**Comment by sepulworld** [comment]
Another option we will be exploring...

https://github.com/kubernetes/autoscaler/blob/d4a6664b389b052293de8f2c0d16839564911e1f/cluster-autoscaler/FAQ.md#i-have-a-couple-of-pending-pods-but-there-was-no-scale-up

basically, we will move over to 3 ASGs, 1 per AZ (what @AceHack mentions above), and let the one statefulset generate by Solr-operator do its thing. Cluster-autoscaler will keep a balance between AZs and should keep us with pods that come online fast without PV toleration issues. Ill follow up with our findings after we test this out.

**Comment by HoustonPutman** [comment]
Thanks for the link @sepulworld. Let's move this discussion over to #53, unless y'all think that we should block this PR until we can figure out a way to do this availability zone thing.

I think that the work for that is very important, but it could be done in separate PRs from this.

**Comment by janhoy** [comment]
Please be aware of https://cwiki.apache.org/confluence/display/SOLR/SIP-8+Autoscaling+policy+engine+V2 in this work - autoscaling may be re-built for solr 9

**Comment by HoustonPutman** [comment]
Thanks for linking this! It's definitely something to keep in mind. Especially if the operator/kubernetes could help handle the external orchestration.

**Comment by HoustonPutman** [comment]
Closing as Autoscaling has been deprecated in recent releases of Solr.

**Pull request closed without merging**
