### PR TITLE
Make GcsRepository.gcsCredentialSecret optional

### PR DESCRIPTION
**Pull request by gerlowskija**
There are some circumstances where GCS access can be managed without
explicitly providing a service account key (e.g. when GKE's "Workload
Identity" feature is used to provide auth metadata).

This commit drops the hard requirement on the `gcsCredentialSecret`
property with this in mind.

### CODE REVIEW

**Review by HoustonPutman — CHANGES_REQUESTED** [review]
This looks great!

2 Things:

- Can you add a changelog entry in `helm/solr-operator/Chart.yaml`?
- What version of golang are you using locally? The tests are failing because of the new line in each `generated.deepcopy.go`: `//go:build !ignore_autogenerated`. It seems like you are using a newer version of golang than the operator uses. For this PR do you mind just removing that line in each of the files (`api/v1beta1/zz_generated.deepcopy.go` and `controllers/zk_api/zz_generated.deepcopy.go`). We can upgrade the golang version in another issue/PR.

**Comment by gerlowskija** [comment]
Hmm, looks like I've got `go version go1.17.5 darwin/amd64` locally.

Thanks for the review and the heads up on the build failure - it's been on my list but I hadn't circled back yet.  Gonna address those review comments now.

**Comment by HoustonPutman** [comment]
We could go ahead and upgrade to golang 1.17 as well (though it should be a separate ticket). I was waiting for 1.18, but it will probably be a while until that is good to use in production.

**Review by HoustonPutman — APPROVED** [review]
Looks good to me!

**Pull request merged**
